### ISSUE TITLE
Magento compass to bourbon

### ISSUE THREAD

**Issue by theskillwithin** [jedfoster/bourbon-compass#6]
Hello,

I need help with something.  Magento ships with a compass install, but it is slow because it uses ruby.  I would LOVE to convert this over to using bourbon instead (so I can use libsass in codekit).  

Do you know how I can accomplish this?

**Comment by jedfoster** [comment]
Sorry, no. I don't know anything about Magento. Perhaps you can use Bourbon directly? https://github.com/thoughtbot/bourbon

**Comment by theskillwithin** [comment]
the magento scss files currently are set up to use compass imports and mixins.  I don't know if I can just plop bourbon in there somehow.

**Comment by jedfoster** [comment]
I don't maintain Bourbon, so I can't speak to how to convert an existing project.

This project doesn't do anything more than wrap Bourbon as Compass extension packaged as a Ruby gem for distribution.
